/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#include<timer.h>
#include<Ucglib.h>
static ucg_t ucg;

int main(void)
{
    SystemCoreClockUpdate();        // cấp clock
    TimerInit();                    // để khởi tạo chức năng timer.

    // Khởi tạo LCD
    Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
    ucg_ClearScreen(&ucg);

    ucg_SetFont(&ucg, ucg_font_helvR08_tr);   // lựa chọn font chữ và cỡ chữ
        ucg_SetColor(&ucg, 0, 0, 255, 0);     // chọn màu chữ là màu trắng
        ucg_SetColor(&ucg, 1, 0, 0, 0);           // màu background là màu đen
        ucg_SetRotate180(&ucg);                  // quay màn hình lại 180 độ
        ucg_DrawString(&ucg, 86 , 64 , 0, "DAT DEP TRAI"); // in dòng chữ ra LCD

    /* Loop forever */
    while(1)
    {
        processTimerScheduler();
    }
}
